name: Linux

on:
  pull_request:
    branches:
      - testing

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [x86_64]
    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Dependency Installation
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get install -y build-essential cmake curl git libgl-dev libgl1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxrender-dev x11proto-core-dev unzip

      - name: Build
        run: |
          xmake config --yes --arch=${{ matrix.arch }} --mode=release
          xmake build --yes
      - name: Package
        run: |
          cd build/linux/${{ matrix.arch }}/release/ && zip -r xavine-linux-${{ matrix.arch }}.zip * && mv xavine-linux-${{ matrix.arch }}.zip ../../../../
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            xavine-linux-${{ matrix.arch }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          generateReleaseNotes: true
          tag: test
#          tag: ${{ github.event.pull_request.title }}
          omitBodyDuringUpdate: true
          prerelease: true
          replacesArtifacts: true